[DOCS-493] API Docs Revision
cobalthq/cobalt-api-docs pull request #185
Opened 2023-06-26 12:15 UTC by ana-dashuk-cobalt

Revised API docs to add more consistency, improve the readability, and support a single source of truth.

## Added

- Shortcodes to support a single source of truth for content. Shortcodes are used to reuse the same chunks of content across multiple files.
- Headings to the **Authentication** page to be able to add links to these sections:
  - Personal API Token
  - Organization Token

## Updated

- Revised the following pages to improve the writing style and readability:
  - Introduction
  - API Versions
  - Authentication
  - Events
  - Tokens
  - Pagination
  - Idempotency
  - Errors
  - Partner Integrations
  - Changelog
  - Subscription
- Changed the link to documentation and updated wording for links on the left navigation panel
- Moved callouts from the bottom to the top of each section, set up a shortcode for callouts
- Standardized the description for 201 and 204 response codes
- Renamed some headings to add more consistency:
  - URL Parameters -> Query Parameters
  - Response Fields -> Response Parameters
  - Body -> Request Body
  - Field (in tables) -> Name 
- Made other minor improvements

## Removed

- **Idempotency** from v1. Idempotency is not relevant for v1, POST requests are not supported.

2023-06-28 09:59 UTC, inikolov89 commented on versions/v2/content/idempotency.md
> +All `POST` requests in Cobalt API v2 are idempotent. Idempotency keys are valid for 5 minutes.
This rewrite changes the meaning. The new statement is not true. Not all `POST` requests are idempotent. Only the ones including including the optional idempotency header `Idempotency-Key: <key>` described in https://github.com/cobalthq/cobalt-api-docs/blob/fc2b494cdcbcbc00ba5cee4bac17d0f315718092/versions/v2/content/idempotency.md

2023-06-28 10:01 UTC, inikolov89 commented on versions/v2/content/idempotency.md
> +You can decide how you want to create unique keys, but make sure that you use a secure method.
Please do not change ` entropy to avoid collisions` otherwise this changes the whole meaning

2023-06-28 10:05 UTC, inikolov89 requested changes
Thanks, @ana-dashuk-cobalt! This looks amazing but it is also a big PR :) 

I had a quick look and it seems it will not be enough. There are parts where the meaning is changed and suggestions are removed. I am ok with rewriting the way we say things but not what we say. 

Will have a deeper look as soon as I have some time.

2023-06-28 10:06 UTC, ana-dashuk-cobalt commented on versions/v2/content/idempotency.md
> +All `POST` requests in Cobalt API v2 are idempotent. Idempotency keys are valid for 5 minutes.
> All `POST` requests optionally accept idempotency keys.

Added the original sentence back.

2023-06-28 10:10 UTC, ana-dashuk-cobalt commented on versions/v2/content/idempotency.md
> +You can decide how you want to create unique keys, but make sure that you use a secure method.
@inikolov89 I discovered plagiarism in this paragraph, it was entirely copied from Stripe docs: https://stripe.com/docs/api/idempotent_requests

That's why I rewrote it completely to avoid any issues. If we use content from third-party sources, we must add the source.

2023-06-28 10:14 UTC, inikolov89 commented on versions/v2/content/idempotency.md
> +You can decide how you want to create unique keys, but make sure that you use a secure method.
😂  someone got too inspired. In this case rewrite makes sense.  

@eugenerevzin , @zmomen-cobalt , @grayson-cobalt , @ericcornelissen  this PR looks like something that needs a bit more attention. Should we create a ticket or smth to dedicate some time here. 

I def. think that improving our documentation is very valuable + plagiarism is something we should avoid!

2023-06-28 10:45 UTC, ana-dashuk-cobalt commented on versions/v2/content/idempotency.md
> +You can decide how you want to create unique keys, but make sure that you use a secure method.
Updated this paragraph:

> An idempotency key is a unique value generated by the client. The server uses this key to recognize
subsequent request attempts if the previous attempt failed. You can decide how you want to create unique keys.
We recommend using V4 UUIDs or another random string with enough entropy.

2023-10-26 09:17 UTC, inikolov89 commented
closing this as we are not going to address it for now

2023-10-26 09:17 UTC, closed without merging